// <auto-generated />
using Helpdesk.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helpdesk.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260908074810_TicketRequester")]
    partial class TicketRequester
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Helpdesk.Features.Requesters.Requester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Requesters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Wojciech Król",
                            Login = "wojtek"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Anna Nowak",
                            Login = "ania"
                        });
                });

            modelBuilder.Entity("Helpdesk.Features.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequesterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Title", "RequesterId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Resolved'");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = "normal",
                            RequesterId = 1,
                            Status = "Open",
                            Title = "Pierwsze zgłoszenie"
                        },
                        new
                        {
                            Id = 2,
                            Priority = "high",
                            RequesterId = 2,
                            Status = "Open",
                            Title = "Drugie zgłoszenie!"
                        });
                });

            modelBuilder.Entity("Helpdesk.Features.Tickets.Ticket", b =>
                {
                    b.HasOne("Helpdesk.Features.Requesters.Requester", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requester");
                });
#pragma warning restore 612, 618
        }
    }
}
